trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

stages:
  - stage: Build
    displayName: Build tasks
    jobs:
      - job: Build
        displayName: Build application and docker image
        variables:
          imageName: 'pipelines-spring-boot-docker'
          buildRevision: format('{0:yyyyMMdd}-{1}', pipeline.startTime, Build.SourceVersion)
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            displayName: Package application jar
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: format('-Xmx3072m -revision={0}', buildRevision)
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              goals: 'package'
          - task: Docker@2
            displayName: Build docker image
            inputs:
              repository: $(imageName)
              command: build
              Dockerfile: ./Dockerfile
  - stage: Deploy
    displayName: Deploy tasks
    jobs:
      - deployment: TestDeploy
        displayName: Test deploy step
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo my first deployment
