trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

variables:
  imageName: 'pipelines-spring-boot-docker'

stages:
  - stage: Build
    jobs:
      - job: BuildApplication
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              goals: 'package'
      - job: BuildDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              repository: $(imageName)
              command: build
              Dockerfile: ./Dockerfile
  - stage: Deploy
    jobs:
      - deployment: TestDeploy
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo my first deployment
